#!/usr/bin/python3

>>> test = __import__('7-base_geometry').BaseGeometry
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> test.integer_validator("name", 1)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> test.integer_validator("a3aw3", "1")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> test.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'


>>> test.integer_validator("value", "1")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> test.area(1)
Traceback (most recent call last):
...
Exception: area() is not implemented


>>> test.area()
Traceback (most recent call last):
...
TypeError: area() missing 1 required positional argument: 'self'

>>> test.integer_validator("myint", 12) 
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> test.integer_validator("width", 89)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator("myint", 12) 

>>> bg.integer_validator("width", 89)

>>> bg.integervalidator("myint", 12)
Traceback (most recent call last):
...
AttributeError: 'BaseGeometry' object has no attribute 'integervalidator'

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("age", -4)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("age", 13.5)
Traceback (most recent call last):
...
TypeError: age must be an integer


>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented


>>> bg.integer_validator("age")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


>>> bg.integer_validator("age", True)
Traceback (most recent call last):
...
TypeError: age must be an integer


>>> bg.integer_validator("age", -4)
Traceback (most recent call last):
...
ValueError: age must be greater than 0


>>> print(dir(bg))
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'area', 'integer_validator']


>>> bg.integer_validator('age', (4,))
Traceback (most recent call last):
...
TypeError: age must be an integer

>>> bg.integer_validator('age', [2])
Traceback (most recent call last):
...
TypeError: age must be an integer

>>> bg.integer_validator('age', {4,1})
Traceback (most recent call last):
...
TypeError: age must be an integer

>>> bg.integer_validator('age', None)
Traceback (most recent call last):
...
TypeError: age must be an integer